apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbuddy-api-staging
  namespace: eventbuddy-staging
  labels:
    app: eventbuddy
    component: api
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eventbuddy
      component: api
      environment: staging
  template:
    metadata:
      labels:
        app: eventbuddy
        component: api
        environment: staging
    spec:
      containers:
      - name: eventbuddy-api
        image: us-central1-docker.pkg.dev/hypnotic-surfer-468513-a0/eventbuddy-repo/eventbuddy:develop
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: http
        envFrom:
        - configMapRef:
            name: eventbuddy-staging-config
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: eventbuddy-staging-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: eventbuddy-staging-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: eventbuddy-staging-secrets
              key: jwt-secret
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: eventbuddy-staging-secrets
              key: sendgrid-api-key
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 6
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 1001