apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbuddy-api
  namespace: eventbuddy
  labels:
    app: eventbuddy
    component: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eventbuddy
      component: api
  template:
    metadata:
      labels:
        app: eventbuddy
        component: api
    spec:
      containers:
      - name: eventbuddy-api
        image: us-central1-docker.pkg.dev/hypnotic-surfer-468513-a0/eventbuddy-repo/eventbuddy:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: eventbuddy-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: eventbuddy-config
              key: PORT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: eventbuddy-config
              key: LOG_LEVEL
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 1001