apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: eventbuddy-staging
  labels:
    app: postgres
    environment: staging
data:
  init-db.sql: |
    -- Initialize EventBuddy Database
    -- This script runs when PostgreSQL container starts

    -- Enable required extensions
    CREATE EXTENSION IF NOT EXISTS "citext";

    -- Database is ready for Prisma migrations
    SELECT 'EventBuddy database initialized with citext extension' AS status;